name: Build for Android

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build ${{matrix.arch}}"

    runs-on: ubuntu-latest
    env:
      #ANDROID_NDK_HOME: "${ANDROID_SDK_ROOT}/ndk-bundle"
      ANDROID_NDK_HOME: "/home/runner/work/tar/tar/android-ndk-r25"

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo mkdir /usr/tmp
          sudo apt update
          sudo apt install clang-tools-6.0 curl gdb lcov libarchive-dev libtalloc-dev sloccount strace swig uthash-dev python3-dev python3 python2 build-essential lzop git autotools-dev autopoint po4a
          mkdir /tmp/build
          
          wget https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip android-ndk-r25-linux.zip
          
          wget https://libarchive.org/downloads/libarchive-3.6.1.tar.gz
          tar -xvf libarchive-3.6.1.tar.gz
          
          wget https://www.samba.org/ftp/talloc/talloc-2.3.4.tar.gz
          tar -xvf talloc-2.3.4.tar.gz
          
          wget https://download.gnome.org/sources/libxml2/2.9/libxml2-2.9.9.tar.xz
          tar -xf libxml2-2.9.9.tar.xz
          
          wget http://ports.ubuntu.com/pool/main/p/python3.8/libpython3.8-dev_3.8.2-1ubuntu1_arm64.deb
          dpkg -x libpython3.8-dev_3.8.2-1ubuntu1_arm64.deb libpython3-8-extracted
          #sudo cp -r libpython3-8-extracted/usr/include/aarch64-linux-gnu/ /usr/include/
          sudo mkdir /usr/include/aarch64-linux-gnu/python3.8/
          sudo cp libpython3-8-extracted/usr/include/aarch64-linux-gnu/python3.8/pyconfig.h /usr/include/aarch64-linux-gnu/python3.8/pyconfig.h
          cp libpython3-8-extracted/usr/include/aarch64-linux-gnu/python3.8/pyconfig.h libxml2-2.9.9/include
          cp libpython3-8-extracted/usr/include/aarch64-linux-gnu/python3.8/pyconfig.h libxml2-2.9.9/include/libxml

      - name: Build libexpat
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          git clone https://github.com/libexpat/libexpat
          cd libexpat/expat
          chmod +x buildconf.sh
          ./buildconf.sh
          ./configure --prefix=/usr --host $TARGET
          make
          sudo make install

      - name: Build liblzma
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          git clone https://git.tukaani.org/xz.git
          cd xz
          chmod +x autogen.sh
          ./autogen.sh
          chmod +x configure
          ./configure --prefix=/usr --host $TARGET
          make
          sudo make install

      - name: Build libxml2
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          #wget https://download.gnome.org/sources/libxml2/2.9/libxml2-2.9.9.tar.xz
          #tar -xf libxml2-2.9.9.tar.xz
          cd libxml2-2.9.9
          chmod +x configure
          ./configure --prefix=/usr --without-zlib --without-lzma --host $TARGET
          make
          sudo make install

      - name: Build libtalloc
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          #wget https://www.samba.org/ftp/talloc/talloc-2.3.4.tar.gz
          #tar -xvf talloc-2.3.4.tar.gz
          cd talloc-2.3.4
          cat <<EOF > cross-answers.txt
          Checking uname sysname type: "Linux"
          Checking uname machine type: "dontcare"
          Checking uname release type: "dontcare"
          Checking uname version type: "dontcare"
          Checking simple C program: OK
          building library support: OK
          Checking for large file support: OK
          Checking for -D_FILE_OFFSET_BITS=64: OK
          Checking for WORDS_BIGENDIAN: OK
          Checking for C99 vsnprintf: OK
          Checking for HAVE_SECURE_MKSTEMP: OK
          rpath library support: OK
          -Wl,--version-script support: FAIL
          Checking correct behavior of strtoll: OK
          Checking correct behavior of strptime: OK
          Checking for HAVE_IFACE_GETIFADDRS: OK
          Checking for HAVE_IFACE_IFCONF: OK
          Checking for HAVE_IFACE_IFREQ: OK
          Checking getconf LFS_CFLAGS: OK
          Checking for large file support without additional flags: OK
          Checking for working strptime: OK
          Checking for HAVE_SHARED_MMAP: OK
          Checking for HAVE_MREMAP: OK
          Checking for HAVE_INCOHERENT_MMAP: OK
          Checking getconf large file support flags work: OK
          EOF
          chmod +x configure
          ./configure --prefix=/usr --disable-rpath --disable-python --cross-compile --cross-answers=cross-answers.txt --host $TARGET
          make
          sudo make install
          
          
      - name: Build libarchive
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          export CFLAGS="-Wno-error"
          #wget https://libarchive.org/downloads/libarchive-3.6.1.tar.gz
          #tar -xvf libarchive-3.6.1.tar.gz
          cd libarchive-3.6.1
          chmod +x configure
          ./configure --prefix=/usr --host $TARGET
          make
          sudo make install

      - name: Build
        run: |
          export TOOLCHAIN=/home/runner/work/proot/proot/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          env LDFLAGS="" make -C src loader.elf loader-m32.elf build.h
          env CFLAGS="--coverage -Wno-error" LDFLAGS="--coverage" make -C src proot

      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: build_${{matrix.arch}}
          path: /home/runner/work/proot/proot/src
