name: Build for Android

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch64" ]
      fail-fast: false

    name: "Build ${{matrix.arch}}"

    runs-on: ubuntu-latest
    env:
      #ANDROID_NDK_HOME: "${ANDROID_SDK_ROOT}/ndk-bundle"
      ANDROID_NDK_HOME: "/home/runner/work/tar/tar/android-ndk-r25"

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo mkdir /usr/tmp
          sudo apt update
          sudo apt install clang-tools-6.0 curl gdb lcov libarchive-dev libtalloc-dev sloccount strace swig uthash-dev python3-dev lzop libexpat-dev
          mkdir /tmp/build
          
          wget https://dl.google.com/android/repository/android-ndk-r25-linux.zip
          unzip android-ndk-r25-linux.zip

      - name: Info
        run: sloccount --details .

      - name: Build
        run: |
          export TOOLCHAIN=/home/runner/work/tar/tar/android-ndk-r25/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=aarch64-linux-android
          export API=28
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export AS=$CC
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          env CFLAGS="-static" PREFIX=/usr/tmp make -C src loader.elf loader-m32.elf build.h
          env CFLAGS="--coverage -Wno-error" LDFLAGS="--coverage -static" PREFIX=/usr/tmp make -C src proot V=1
          sudo make install

      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: build_${{matrix.arch}}
          path: /usr/tmp
